name: dvec
type: baseline  # meta/baseline

adapt:
  speaker_emb: dvec # shared/table/encoder/dvec
  modules: []

  ways: 1
  shots: 5
  queries: 5
  steps: 5
  lr: 0.001
  meta_batch_size: 1

  test:
    queries: 1
    steps: 0 # max adaptation steps for testing
