dataset: "miniLibriTTS"
lang_id: 0

path:
  corpus_path: "/home/r06942045/myData/LibriTTS"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/LibriTTS"
  preprocessed_path: "./preprocessed_data/miniLibriTTS"

subsets:
  train: "test-clean"
  val: "test-clean"
  test: "test-clean"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: Null # set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
